#!/bin/bash

echo "================================================================================"
echo "🚀 AVM 프로덕션 모니터링 시스템 시작"
echo "================================================================================"

echo ""
echo "📊 모니터링 시작 순서:"
echo ""
echo "1️⃣  API 서버 시작 중..."
echo "    포트: 8000"
echo "    URL: http://localhost:8000"
echo ""
echo "2️⃣  대시보드 준비 중..."
echo "    대시보드: http://localhost:8000/dashboard"
echo "    갱신 주기: 30초 (자동)"
echo ""
echo "3️⃣  성능 모니터링 활성화 중..."
echo "    메트릭: R², RMSE, MAE, MAPE, 응답시간, 처리량"
echo "    로그: logs/performance_history.jsonl"
echo ""
echo "4️⃣  자동 재학습 스케줄러 준비 중..."
echo "    스케줄: 매주 목요일 10:00 UTC"
echo "    명령: python scripts/looping_scheduler.py --mode scheduler"
echo ""
echo "================================================================================"
echo ""
echo "✅ 모니터링 시작 준비 완료!"
echo ""
echo "📌 사용법:"
echo "   1. 이 스크립트가 실행되는 Terminal에서 API 서버 운영"
echo "   2. 다른 Terminal에서: python scripts/looping_scheduler.py --mode scheduler"
echo "   3. 브라우저에서: http://localhost:8000/dashboard"
echo ""
echo "🎯 주요 기능:"
echo "   • 실시간 성능 차트 (30초 갱신)"
echo "   • 실시간 알림 로그"
echo "   • 모델 성능 비교"
echo "   • 예측 통계"
echo ""
echo "================================================================================"

# API 서버 시작
echo ""
echo "🌐 API 서버 시작 중..."
echo ""

python -m uvicorn scripts.api_server:app --host 0.0.0.0 --port 8000 --reload
